language: node_js
sudo: false

os:
  - linux

node_js:
  - 10.15.3

cache:
  yarn: true
  directories:
    - node_modules

script:
  - npm run build

after_script:
  - npm run deploy

#指定分支，只有指定的分支提交时才会运行脚本
branches:
  only:
    - master
