on:
  push:
    branches:
      - "master"
name: Build
jobs:
  deploy:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install
        uses: Borales/actions-yarn@master
        with:
          args: install
      - name: Build
        uses: actions/setup-node@v1
        with:
          node-version: "10.15.3"
      - run: npm run build