on:
  push:
    branches:
      - "master"
name: build
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install
        uses: Borales/actions-yarn@master
        with:
          args: install
      - name: Build
        uses: actions/setup-node@v1
        with:
          node-version: "10.15.3"
      - run: npm run build
      - name: Deploy to axetroy.github.io
        uses: axetroy/ghpages@master
        env:
          BUILD_DIR: build
          REPOSITORY: axetroy/axetroy.github.io
          GH_PAT: ${{ secrets.GH_PAT }}

      - name: Copy CNAME
        run: copy ./CNAME ./build/CNAME

      - name: Deploy to blog.axetroy.xyz
        uses: maxheld83/ghpages@v0.2.1
        env:
          BUILD_DIR: build
          GH_PAT: ${{ secrets.GH_PAT }}