on:
  push:
    branches:
      - "master"
name: Deploy to website
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Install
        uses: Borales/actions-yarn@master
        with:
          args: install
      - name: Build
        uses: actions/setup-node@v1
        with:
          node-version: "10.15.3"
      - run: ls -lh && pwd
      - name: Deploy
        uses: maxheld83/ghpages@v0.2.1
        env:
          BUILD_DIR: build
          GITHUB_REPOSITORY: axetroy/axetroy.github.io
          GH_PAT: ${{ secrets.GITHUB_TOKEN }}